<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/07 14:48:51
sfConfig::add(array(
  'mod_medicijnbeheer_enabled' => true,
  'mod_medicijnbeheer_view_class' => 'sfPHP',
));
