<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/10 06:59:10
sfConfig::add(array(
  'mod_medicijnbeheer_enabled' => true,
  'mod_medicijnbeheer_view_class' => 'sfPHP',
));
